# Changes here will be overwritten by Copier
_commit: '4483535'
_src_path: https://github.com/nialov/nialov-py-template.git
classifier: 'Topic :: Scientific/Engineering :: GIS'
description: Fracture Network Analysis
email: nikolasovaskainen@gmail.com
full_name: Nikolas Ovaskainen
github_account: nialov
keyword: data
package: fractopo
year: 2020
