name: fractopo

channels:
  - conda-forge

# Changes here should be kept in sync with ./pyproject.toml
dependencies:
  - python >=3.8,<3.12
  - click
  - geopandas >=0.11.1,<1.0.0
  - matplotlib-base
  - numpy
  - pandas
  - powerlaw
  - pygeos >=0.13.0,<1.0.0
  - python-ternary
  - rich
  - scikit-learn
  - scipy
  - seaborn
  - shapely >=1.8.0,<2.0.0
  - typer
  - joblib
  # Dependencies for testing
  - hypothesis
  - pytest
  - pytest-regressions
