on:
  push:
    branches: [$default-branch]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build documentation
        run: |
          nix build .#fractopo.doc --out-link result
          cp -Lr --no-preserve=mode,ownership,timestamps ./result/share/doc/ ./docs
      - uses: actions/upload-pages-artifact@v2
        with:
          # Upload folder with static docs
          path: "docs"
      - uses: actions/configure-pages@v3
      - id: deployment
        uses: actions/deploy-pages@v2
